services:
  fast-api:
    image: imraghav/fastapi:latest
    container_name: fast-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped